services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: gittrack-bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3001"
    volumes:
      - ../logs:/app/logs
    networks:
      - gittrack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gittrack-network:
    driver: bridge 